/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-prowess
 *
 * SPDX-License-Identifier: MIT
 *
 */

#ifndef INCLUDED_PROWESS_API_H
#define INCLUDED_PROWESS_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_prowess_EXPORTS
#define PROWESS_API __GR_ATTR_EXPORT
#else
#define PROWESS_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_PROWESS_API_H */
