/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(message_forward.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(afbf54bfd6e902e303cf1f9d9b9f35fd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/prowess/message_forward.h>
// pydoc.h is automatically generated in the build directory
#include <message_forward_pydoc.h>

void bind_message_forward(py::module& m)
{

    using message_forward    = gr::prowess::message_forward;


    py::class_<message_forward, gr::block, gr::basic_block,
        std::shared_ptr<message_forward>>(m, "message_forward", D(message_forward))

        .def(py::init(&message_forward::make),
           D(message_forward,make)
        )
        



        ;




}








