/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(null_sink_latency.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(bc0d52a9d8d33977382594accc98a52c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/prowess/null_sink_latency.h>
// pydoc.h is automatically generated in the build directory
#include <null_sink_latency_pydoc.h>

void bind_null_sink_latency(py::module& m)
{

    using null_sink_latency    = gr::prowess::null_sink_latency;


    py::class_<null_sink_latency, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<null_sink_latency>>(m, "null_sink_latency", D(null_sink_latency))

        .def(py::init(&null_sink_latency::make),
           D(null_sink_latency,make)
        )
        



        ;




}








